# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 328)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_generar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generar.setGeometry(QtCore.QRect(530, 60, 75, 23))
        self.btn_generar.setObjectName("btn_generar")
        self.lbl_shared_key = QtWidgets.QLabel(self.centralwidget)
        self.lbl_shared_key.setGeometry(QtCore.QRect(40, 0, 71, 16))
        self.lbl_shared_key.setObjectName("lbl_shared_key")
        self.lbl_totp = QtWidgets.QLabel(self.centralwidget)
        self.lbl_totp.setGeometry(QtCore.QRect(40, 70, 131, 16))
        self.lbl_totp.setObjectName("lbl_totp")
        self.lbl_time = QtWidgets.QLabel(self.centralwidget)
        self.lbl_time.setGeometry(QtCore.QRect(450, 60, 47, 13))
        self.lbl_time.setObjectName("lbl_time")
        self.lbl_account = QtWidgets.QLabel(self.centralwidget)
        self.lbl_account.setGeometry(QtCore.QRect(440, 0, 61, 16))
        self.lbl_account.setObjectName("lbl_account")
        self.tbl_view = QtWidgets.QTableView(self.centralwidget)
        self.tbl_view.setGeometry(QtCore.QRect(40, 100, 531, 192))
        self.tbl_view.setObjectName("tbl_view")
        self.inp_shared_key = QtWidgets.QLineEdit(self.centralwidget)
        self.inp_shared_key.setGeometry(QtCore.QRect(40, 20, 113, 20))
        self.inp_shared_key.setObjectName("inp_shared_key")
        self.inp_account = QtWidgets.QLineEdit(self.centralwidget)
        self.inp_account.setGeometry(QtCore.QRect(440, 20, 113, 20))
        self.inp_account.setObjectName("inp_account")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_generar.setText(_translate("MainWindow", "Generar"))
        self.lbl_shared_key.setText(_translate("MainWindow", "Shared Key"))
        self.lbl_totp.setText(_translate("MainWindow", "Código generado"))
        self.lbl_time.setText(_translate("MainWindow", "0"))
        self.lbl_account.setText(_translate("MainWindow", "AccountID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
